name: nir-pls
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - ipykernel
  - pip
  - pip:
    - nbstripout